run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - gocritic
    - gci

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(online-subscription-service)
    custom-order: true

issues:
  exclude-use-default: false
  max-same-issues: 0